ktor {
    deployment {
        port = 8080
        port = ${?PORT}
    }
    application {
        modules = [ lt.skautai.ApplicationKt.module ]
    }
}

database {
    url = "jdbc:postgresql://localhost:5432/skautu_inventorius"
    url = ${?DB_URL}
    driver = "org.postgresql.Driver"
    user = "postgres"
    user = ${?DB_USER}
    password = ${DB_PASSWORD}
}

jwt {
    secret = ${JWT_SECRET}
    issuer = "lt.skautai"
    audience = "lt.skautai.app"
    realm = "skautu-inventorius"
}